# Generated by Django 5.1.7 on 2026-04-11 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_type', models.CharField(choices=[('tax', 'Annual Tax'), ('inspection', 'Inspection'), ('insurance', 'Insurance'), ('penalty', 'Penalty')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', 'status'], name='obligations_vehicle_2f9251_idx'), models.Index(fields=['due_date', 'status'], name='obligations_due_dat_36715e_idx')],
            },
        ),
    ]
