# Generated by Django 5.1.7 on 2026-05-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'Pending Verification')], db_index=True, default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('institution_officer', 'Institution Officer'), ('institution_admin', 'Institution Admin'), ('system_admin', 'System Admin')], db_index=True, default='citizen', max_length=30),
        ),
    ]
