# Generated by Django 5.1.7 on 2026-04-11 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('vin', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=50)),
                ('registration_date', models.DateField()),
                ('inspection_expiry', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_transfer', 'Pending Transfer'), ('sold', 'Sold'), ('blocked', 'Blocked')], db_index=True, default='active', max_length=30)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'status'], name='vehicles_ve_owner_i_d81e00_idx'), models.Index(fields=['inspection_expiry'], name='vehicles_ve_inspect_95a9bc_idx'), models.Index(fields=['insurance_expiry'], name='vehicles_ve_insuran_c8665d_idx')],
            },
        ),
    ]
