# Generated by Django 5.1.7 on 2026-05-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='circulation_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='road_tax_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
