# Generated by Django 5.1.7 on 2026-04-11 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration'), ('insurance', 'Insurance'), ('inspection', 'Inspection'), ('sale_contract', 'Sale Contract'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=120)),
                ('file', models.FileField(upload_to='documents/')),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle', 'document_type'], name='documents_d_vehicle_28db18_idx'), models.Index(fields=['expires_at'], name='documents_d_expires_796a52_idx')],
            },
        ),
    ]
